# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fix_species": "data.ipynb",
         "duplicate_ones": "data.ipynb",
         "train_valid_split": "data.ipynb",
         "extract_top_n_classes": "data.ipynb",
         "HappyWhalesDataset": "data.ipynb",
         "FocalLoss": "losses.ipynb",
         "ArcFaceLoss": "losses.ipynb",
         "map_per_image": "metrics.ipynb",
         "map_per_set": "metrics.ipynb",
         "GeM": "models.ipynb",
         "ArcMarginProduct": "models.ipynb",
         "Backbone": "models.ipynb",
         "HappyWhalesModel": "models.ipynb",
         "scheduler_step": "training.ipynb",
         "train_one_epoch": "training.ipynb",
         "train_one_step": "training.ipynb",
         "validate_one_epoch": "training.ipynb",
         "validate_one_step": "training.ipynb",
         "seed_everything": "utils.ipynb",
         "fit_transform_and_dump_label_encoder": "utils.ipynb"}

modules = ["data.py",
           "losses.py",
           "metrics.py",
           "models.py",
           "training.py",
           "utils.py"]

doc_url = "https://pawlowskipawel.github.io/happy_whales/"

git_url = "https://github.com/pawlowskipawel/happy_whales/tree/main/"

def custom_doc_links(name): return None
