# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"HappyWhalesDataset": "data.ipynb",
         "map_per_image": "metrics.ipynb",
         "map_per_set": "metrics.ipynb"}

modules = ["data.py",
           "metrics.py",
           "model.py"]

doc_url = "https://pawlowskipawel.github.io/happy_whales/"

git_url = "https://github.com/pawlowskipawel/happy_whales/tree/main/"

def custom_doc_links(name): return None
