# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/utils.ipynb (unless otherwise specified).

__all__ = ['seed_everything', 'fit_transform_and_dump_label_encoder', 'load_label_encoder']

# Cell
from sklearn.preprocessing import LabelEncoder
import numpy as np
import random
import pickle
import torch
import os

# Cell
def seed_everything(seed=7777):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True

# Cell
def fit_transform_and_dump_label_encoder(labels, encoder_name, dest_dir="."):
    label_encoder = LabelEncoder()

    labels = label_encoder.fit_transform(labels)
    pickle.dump(label_encoder, open(os.path.join(dest_dir, f"{encoder_name}.pickle"), "wb"))

    return labels

# Cell
def load_label_encoder(path):
    return pickle.load(open(path, "rb"))